#cloud-config
# vim: syntax=yaml
#

# The current version of cloud-init in the Hypriot rpi-64 is 0.7.6
# When dealing with cloud-init, it is SUPER important to know the version
# I have wasted many hours creating servers to find out the module I was trying to use wasn't in the cloud-init version I had
# Documentation: http://cloudinit.readthedocs.io/en/0.7.9/index.html

# Set your hostname here, the manage_etc_hosts will update the hosts file entries as well
hostname: node2
manage_etc_hosts: true

# You could modify this for your own user information
users:
  - name: pi
    gecos: "Hypriot Pirate"
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    groups: users,docker,video,input
    plain_text_passwd: hypriot
    lock_passwd: true
    ssh_pwauth: false
    chpasswd: { expire: false }
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYyyyocTJjhM/sH63FMoqo8qU9zRI7vLsx3Syh5Tm6zSQtVV2aF0JcHOP02dsXiC0tRkSM8H/Tumlpq0YJhwtOLqlIEDWkwZp978QO3Alg5RK/CuCwrdIPXe6iZXV7fRupZTsxxwu2JUhZCaS7zqH+CP/a7oNBWUGx75GYv5p3z5h57og6ysjRXHFKELh9tc4GI5GUXkeyjd3nF7AmUAxy84r+ForwgkPLtZ8f0pmC6uMU5kLYDP4XU2LpnwruViGUiavPJa7SQJ/EZLN+3X8RHjA7UP7/gH7K4pYhXvq4r9OUeYy3hoKsUoIGMiY6YYLDuW6YR6IuCzRpJvzLX9Th sinpaout@SinMacbook.local

# # Set the locale of the system
# locale: "en_US.UTF-8"
# locale: "ja_JP.UTF-8"

# # Set the timezone
# # Value of 'timezone' must exist in /usr/share/zoneinfo
# timezone: "America/Los_Angeles"
timezone: "Asia/Tokyo"

# # Update apt packages on first boot
# package_update: true
# package_upgrade: true
# package_reboot_if_required: true
package_upgrade: false

runcmd:
  # Pickup the hostname changes
  - 'systemctl restart avahi-daemon'
