#!/usr/bin/env ansible-playbook

- hosts: node2
  become: True
  tasks:
    - name: insert ip address fixing setting
      blockinfile:
        path: /etc/dhcpcd.conf
        insertafter: EOF
        content: |
          interface eth0
          static ip_address=192.168.11.103/24
          static routers=192.168.11.1
          static domain_name_servers=8.8.8.8
    - name: restart server
      become: true
      command: sleep 5 && reboot
      ignore_errors: true
      async: 1
      poll: 0
  handlers:
  - name: restart nginx
    service: name=nginx state=restarted